-- MySQL Script generated by MySQL Workbench
-- Wed Feb  1 14:18:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pensiondb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pensiondb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pensiondb` DEFAULT CHARACTER SET utf8 ;
USE `pensiondb` ;

-- -----------------------------------------------------
-- Table `pensiondb`.`pensions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pensiondb`.`pensions` (
  `id` INT NOT NULL,
  `type` VARCHAR(100) NOT NULL,
  `grandeur` VARCHAR(100) NOT NULL,
  `nb_animal_prst` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pensiondb`.`animaux`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pensiondb`.`animaux` (
  `id` INT NOT NULL,
  `type` VARCHAR(100) NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  `age` VARCHAR(45) NOT NULL,
  `pensions_id` INT NOT NULL,
  PRIMARY KEY (`id`, `pensions_id`),
  INDEX `fk_animaux_pensions_idx` (`pensions_id` ASC) VISIBLE,
  CONSTRAINT `fk_animaux_pensions`
    FOREIGN KEY (`pensions_id`)
    REFERENCES `pensiondb`.`pensions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pensiondb`.`prestations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pensiondb`.`prestations` (
  `id` INT NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  `prix` VARCHAR(100) NOT NULL,
  `durée` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `pensiondb`.`pensions`
-- -----------------------------------------------------
START TRANSACTION;
USE `pensiondb`;
INSERT INTO `pensiondb`.`pensions` (`id`, `type`, `grandeur`, `nb_animal_prst`) VALUES (1, 'Canine', '100', '3');
INSERT INTO `pensiondb`.`pensions` (`id`, `type`, `grandeur`, `nb_animal_prst`) VALUES (2, 'Féline', '100', '2');
INSERT INTO `pensiondb`.`pensions` (`id`, `type`, `grandeur`, `nb_animal_prst`) VALUES (3, 'Nac', '20', '2');

COMMIT;


-- -----------------------------------------------------
-- Data for table `pensiondb`.`animaux`
-- -----------------------------------------------------
START TRANSACTION;
USE `pensiondb`;
INSERT INTO `pensiondb`.`animaux` (`id`, `type`, `nom`, `age`, `pensions_id`) VALUES (1, 'Chien', 'Bob', '2ans', 1);
INSERT INTO `pensiondb`.`animaux` (`id`, `type`, `nom`, `age`, `pensions_id`) VALUES (2, 'Chat', 'Romeo', '1ans', 2);
INSERT INTO `pensiondb`.`animaux` (`id`, `type`, `nom`, `age`, `pensions_id`) VALUES (3, 'Chat', 'Loulou', '12ans', 2);
INSERT INTO `pensiondb`.`animaux` (`id`, `type`, `nom`, `age`, `pensions_id`) VALUES (4, 'Chien', 'Doggy', '4ans', 1);
INSERT INTO `pensiondb`.`animaux` (`id`, `type`, `nom`, `age`, `pensions_id`) VALUES (5, 'Nac', 'Griiffon', '2ans', 3);
INSERT INTO `pensiondb`.`animaux` (`id`, `type`, `nom`, `age`, `pensions_id`) VALUES (6, 'Nac', 'Griffette', '1ans', 3);
INSERT INTO `pensiondb`.`animaux` (`id`, `type`, `nom`, `age`, `pensions_id`) VALUES (7, 'Chien', 'Popole', '7ans', 1);

COMMIT;

