-- MySQL Script generated by MySQL Workbench
-- Thu Feb  2 10:28:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pensiondb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pensiondb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pensiondb` DEFAULT CHARACTER SET utf8 ;
USE `pensiondb` ;

-- -----------------------------------------------------
-- Table `pensiondb`.`pensions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pensiondb`.`pensions` ;

CREATE TABLE IF NOT EXISTS `pensiondb`.`pensions` (
  `idPensions` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(100) NOT NULL,
  `grandeur` VARCHAR(100) NOT NULL,
  `nbAnimalPrst` VARCHAR(45) NOT NULL,
  `imgPension` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`idPensions`))
ENGINE = InnoDB;
    ALTER TABLE `pensiondb`.`pensions`
ALTER COLUMN imgPension
SET
    DEFAULT "image-animaux-default.jpg";

-- -----------------------------------------------------
-- Table `pensiondb`.`animaux`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pensiondb`.`animaux` ;

CREATE TABLE IF NOT EXISTS `pensiondb`.`animaux` (
  `idAnimaux` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(100) NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  `age` VARCHAR(45) NOT NULL,
  `imgAnimaux` VARCHAR(1024) NOT NULL,
  `pensionsId` INT NOT NULL,
  PRIMARY KEY (`idAnimaux`, `pensionsId`),
  INDEX `fk_animaux_pensionsIdx` (`pensionsId` ASC) VISIBLE,
  CONSTRAINT `fk_animaux_pensions`
    FOREIGN KEY (`pensionsId`)
    REFERENCES `pensiondb`.`pensions` (`idPensions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `pensiondb`.`animaux`
ALTER COLUMN imgAnimaux
SET
    DEFAULT "image-animaux-default.jpg";

    ALTER TABLE `pensiondb`.`animaux`
ALTER COLUMN pensionsId
SET
    DEFAULT "2";
-- -----------------------------------------------------
-- Table `pensiondb`.`prestations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pensiondb`.`prestations` ;

CREATE TABLE IF NOT EXISTS `pensiondb`.`prestations` (
  `idPrestations` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `prix` VARCHAR(100) NOT NULL,
  `durée` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idPrestations`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `pensiondb`.`pensions`
-- -----------------------------------------------------
START TRANSACTION;
USE `pensiondb`;
INSERT INTO `pensiondb`.`pensions` (`idPensions`, `type`, `grandeur`, `nbAnimalPrst`, `imgPension`) VALUES (1, 'Canine', '100', '3', 'image-chien-pension.jpg');
INSERT INTO `pensiondb`.`pensions` (`idPensions`, `type`, `grandeur`, `nbAnimalPrst`, `imgPension`) VALUES (2, 'Féline', '100', '2', 'image-chat-pension.jpg');
INSERT INTO `pensiondb`.`pensions` (`idPensions`, `type`, `grandeur`, `nbAnimalPrst`, `imgPension`) VALUES (3, 'Nac', '20', '2', DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pensiondb`.`animaux`
-- -----------------------------------------------------
START TRANSACTION;
USE `pensiondb`;
INSERT INTO `pensiondb`.`animaux` (`idAnimaux`, `type`, `nom`, `age`, `imgAnimaux`, `pensionsId`) VALUES (1, 'Chien', 'Bob', '2ans', DEFAULT, 1);
INSERT INTO `pensiondb`.`animaux` (`idAnimaux`, `type`, `nom`, `age`, `imgAnimaux`, `pensionsId`) VALUES (2, 'Chat', 'Romeo', '1ans', DEFAULT, 2);
INSERT INTO `pensiondb`.`animaux` (`idAnimaux`, `type`, `nom`, `age`, `imgAnimaux`, `pensionsId`) VALUES (3, 'Chat', 'Loulou', '12ans', DEFAULT, 2);
INSERT INTO `pensiondb`.`animaux` (`idAnimaux`, `type`, `nom`, `age`, `imgAnimaux`, `pensionsId`) VALUES (4, 'Chien', 'Doggy', '4ans', DEFAULT, 1);
INSERT INTO `pensiondb`.`animaux` (`idAnimaux`, `type`, `nom`, `age`, `imgAnimaux`, `pensionsId`) VALUES (5, 'Nac', 'Griiffon', '2ans', DEFAULT, 3);
INSERT INTO `pensiondb`.`animaux` (`idAnimaux`, `type`, `nom`, `age`, `imgAnimaux`, `pensionsId`) VALUES (6, 'Nac', 'Griffette', '1ans', DEFAULT, 3);
INSERT INTO `pensiondb`.`animaux` (`idAnimaux`, `type`, `nom`, `age`, `imgAnimaux`, `pensionsId`) VALUES (7, 'Chien', 'Popole', '7ans', DEFAULT, 1);

COMMIT;

